config/routes.rb
Koreantyper::Application.routes.draw do
  devise_for :users

  root :to => 'welcome#index'

  resources :races, only: [:new, :create]

  resources :passages, only: [:show]

end

app/models/passage.rb
class Passage < ActiveRecord::Base
end

app/models/race.rb
class Race < ActiveRecord::Base
end

app/models/race_passage.rb
class RacePassage < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :username, :login
  # attr_accessible :title, :body

  attr_accessor :login

  validates_presence_of :username

  has_many :race_passages, through: :race

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/passages_controller.rb
class PassagesController < ActionController::Base
  def show
    @passage = Passage.find(params[:id])
  end
end

app/controllers/races_controller.rb
class RacesController < ActionController::Base
  def new
    @race = Race.new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Korean Typer</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/passages/show.html.erb
<%= @passage.body %>

<div class="start">Start</div>

app/views/races/new.html.erb
<%- @passage = Passage.first %>
<%= link_to "Easy", passage_path(@passage) %>

app/views/welcome/index.html.erb
<%= link_to "Start Race", new_race_path %>